### ISSUE TITLE
Error: "A separate request to update this alarm is in progress"

### ISSUE THREAD

**Issue by barnesrobert** [aws-quickstart/quickstart-compliance-cis-benchmark#12]
I get this error indiscriminately creating the UnauthorizedApiCallsAlarm resource when launching the template. The stack launches successfully on most occasions.

![unauthorizedapicallsalarm](https://user-images.githubusercontent.com/10154662/37605316-ead5cee6-2b60-11e8-80ef-7cbfb2668d2c.png)

**Comment by barnesrobert** [comment]
Any updates here? I continue to see this intermittently. Thank you.

**Comment by nterry** [comment]
See https://github.com/hashicorp/terraform/issues/10689 for more details

**Comment by robnand** [comment]
Thanks for bringing this up Rob.

I've made some changes to add "DependsOn" for the CloudWatch alarms so each alarm is created in sequence. This should prevent this error from occurring in the future.

Andrew
