### ISSUE TITLE
Cloudwatch Alerts for Trusted Advisor

### ISSUE THREAD

**Issue by jimsmith** [aws-quickstart/quickstart-compliance-cis-benchmark#13]
Hi Team,

Can you please incorporate this into CIS benchmark please ?

https://gist.github.com/jimsmith/7aa9a99b2ba6372fcab2de00aa16c1e3

This Template creates an Amazon Cloudwatch Alert for Trusted Advisor open ports, protocols, IAM credentials not rotated in 90 days and must be created in us-east-1.

**Comment by jimsmith** [comment]
bump

**Comment by aravindkaws** [comment]
Hi Jim,
Thanks for reaching out and providing your feature request. We will add this to the backlog of features to be built.
