### ISSUE TITLE
Feedback: AWS Organizations & Aggregation - Questions

### ISSUE THREAD

**Issue by omahonyb** [aws-quickstart/quickstart-compliance-cis-benchmark#14]
Hey folks. Came across this recently and it looks very good. I do have a few questions though. As a preamble we have AWS Organizations set up with 30+ accounts. We are looking/hoping to manage security & compliance from a single account. We hope to keep Cloudwatch, GuardDuty, Config, Inspector and Trusted Advisor in a single place. Also potentially AWS Health and anything else that would be better aggregated so we don't have to mess around with switching accounts. So here goes:

#1 Root account requiring MFA:
Organizations by default does not give you root credentials, instead using Assume Role. Is it possible to change this check to see if the root account has never logged in etc? [We see no reason to actually logging in as root, and having 30+ MFA keys that are never used]

#2 Multi Account:
The CloudFormation templates for this are fantastic, albeit I have only used it once so far. Are there any plans to simplify the templates  for multi account deployment? With the Config aggregator announced in SF yesterday, we are hoping to use that. Cross-Account CW events have previously been available [although I am unsure of CW alarms, as this is all still pretty new to me]

I did have other queries but forgot them on the way home this evening.

**Comment by aravindkaws** [comment]
Hello,

The current template provides a CloudWatch alarm for any Root user activity in the account. We would not be able to change the existing "Root Account requiring MFA" to just check for root account being used as this would be deviating from the CIS Std controls.

We are evaluating the Config aggregator feature and have a logged a backlog item for this.
