### ISSUE TITLE
CIS 1.12 - 1.14 does not account for base64 encoding

### ISSUE THREAD

**Issue by kmonihen** [aws-quickstart/quickstart-compliance-cis-benchmark#19]
The client call to get_credential_report() does not account for the content being base64 encoded.

[Code](https://github.com/aws-quickstart/quickstart-compliance-cis-benchmark/blob/master/templates/cis-benchmark.template#L626):
`
content = client.get_credential_report()['Content']
users = content.splitlines()
`

[Per boto3 docs](https://boto3.readthedocs.io/en/latest/reference/services/iam.html#IAM.Client.get_credential_report):
> Content (bytes) --
> Contains the credential report. The report is Base64-encoded.

**Comment by kmonihen** [comment]
Sorry, I accidentally closed it. This is the messy solution I'm using:

`users = base64.standard_b64decode(content).decode("utf-8").splitlines()`

Hope that helps!

**Comment by kmonihen** [comment]
I wasn't testing this properly. I ran another test and found that botocore automatically decodes base64 blobs, so this is not an issue.

**Comment by agamzn** [comment]
All good. We're here if something else crops up. Enjoy your weekend.
