### ISSUE TITLE
CIS rules continue to report deleted resources as non compliant

### ISSUE THREAD

**Issue by xor007** [aws-quickstart/quickstart-compliance-cis-benchmark#20]
Hi.

We have tried to use the CIS quickstart and we notice that even after deleting non compliant resources, they still appear in reports as non compliant. AWS advises that the lambda's are not checking for deleted resources:

_"In order for a custom rule to return a compliance state, it must be first defined in the Lambda function code of your function. There are 3 states that need to be defined in your Lambda function source code:

NOT_APPLICABLE
NON_COMPLIANT
COMPLIANT

You can declare a resource state for 'configurationItemStatus' in order to tell Config to return a different compliance state for that state.

Example:

    # Check if resource was deleted
    if configuration_item['configurationItemStatus'] == "ResourceDeleted":
        return {
            "compliance_type": "NOT_APPLICABLE",
            "annotation": "This resource was deleted."
        }

For full source code of the custom rule containing such declaration please visit awslabs."_

**Comment by robnand** [comment]
Hi,

Thanks for the feedback, we appreciate you taking the time to let us know about this.

Can you please clarify which Config rules you are seeing this behaviour on?

Thanks

**Comment by robnand** [comment]
Hi,

Thanks for the feedback, we've made some changes to the Lambda functions for the Config rules and they now check for deleted resources.

Andrew

**Comment by manjishri** [comment]
Hi 

I am facing same issue and need help to fix lambda code. Please help me to tweak lambda so that it will not check for deleted resources.

Shriram

**Comment by robnand** [comment]
Hi Shriram,

Thanks for the the comment!

To confirm we have already made changes to stop checking for deleted resources. Can you confirm which resources are still being detected?

**Comment by manjishri** [comment]
Hi Robnand,

Thanks for updates.

I cleaned up certain non-compliant users and data was reflected as deleted users (with random ids) are non compliant. Further on investigation, i find that the old data is being reflected.

I cleared old data and then in re-run, deleted resources are not reflected. 

Do i need to clear old data on every delete of non-compliant resources?

Shriram
