### ISSUE TITLE
Deploy Level 1 & Level 2 controls

### ISSUE THREAD

**Issue by luistapia6-11** [aws-quickstart/quickstart-compliance-cis-benchmark#23]
This is a great template! As far as I can tell it only lets me deploy Level 1 or Level 2 controls and not both at the same time. Am I doing something wrong? Is there a way to deploy both Level 1 & 2 controls?

Thanks!

**Comment by robnand** [comment]
Hi, thanks for the feedback!

The templates are designed to implement either Level 1 or Level 2 controls. If you chose Level 1, only the Level 1 controls will be implemented. If you chose Level 2, both Level 1 and Level 2 controls will be implemented.

**Comment by luistapia6-11** [comment]
Sorry about that...Thanks for clarifying! I must have missed that when I tested it. My bad. This is the best CIS template I've found so far. Thank you for your efforts!
