### ISSUE TITLE
Config rules for MFA check on root should be enabled for level 1

### ISSUE THREAD

**Issue by ajaymehta76** [aws-quickstart/quickstart-compliance-cis-benchmark#24]
As per the AWS CIS benchmark published at https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf items 1.12, 1.13 and 1.14 are considered Level 1, however the template only enables the corresponding config rules if profile is set to level 2.

**Comment by robnand** [comment]
Hi,

Thanks for the feedback, we really appreciate it!

You are correct that controls 1.12, 1.13, and 1.14 are Level 1 controls but were implemented as Level 2 controls. We have updated the CloudFormation templates used so that these controls are now implemented at Level 1.

Thanks again!
