### ISSUE TITLE
Disabled console access is flagged as violating CIS-RotateUserPasswords

### ISSUE THREAD

**Issue by kadrach** [aws-quickstart/quickstart-compliance-cis-benchmark#25]
I have an IAM user with `"PasswordLastUsed": "2017-04-21..."`. This user does not have a login profile, no password and does not have console access.

It appears that disabling console access for a user that's previously had it does not clear the `PasswordLastUsed` attribute.

https://github.com/aws-quickstart/quickstart-compliance-cis-benchmark/blob/master/templates/cis-benchmark.template#L377

**Comment by robnand** [comment]
Hi,

Thanks for reporting this, we really appreciate the contributions the community makes to the Quick Start!  We have pushed a fix for this and it's not live in the master branch.

Thanks
