### ISSUE TITLE
CIS-EvaluateFullAdminPrivilegesPolicies - False positives

### ISSUE THREAD

**Issue by owenbarnes** [aws-quickstart/quickstart-compliance-cis-benchmark#30]
This line in the lambda function for the above benchmark appears to be generating false positives:

`if jmespath.search('PolicyVersion.Document.Statement[?Effect == \'Allow\' && contains(Resource, \'*\') && contains (Action, \'*\')]', policy_version):
    return_value = 'NON_COMPLIANT'`

An example policy such as the following will be marked as non-compliant, despite it not giving administrator rights:

`      {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "sqs:*"
            ],
            "Resource": "*"
        }`

When I change the lambda code to the following (adding quotes around the *), the policy is marked as compliant:

`if jmespath.search('PolicyVersion.Document.Statement[?Effect == \'Allow\' && contains(Resource, \'"*"\') && contains (Action, \'"*"\')]', policy_version):
    return_value = 'NON_COMPLIANT'`

Am I interpreting this correctly? Is this the best way to fix it?

**Comment by casti3ll** [comment]
Hi, are you still getting false positives? If yes, could you please provide more details?
I do not see the same behavior on my end. Also, the jmespath search function has been tested separately using your example and it is not generating false positives. Thanks!

**Comment by owenbarnes** [comment]
That example wasnt the best one, heres a few that are triggering it:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "events:PutEvents",
                "cloudwatch:PutDashboard",
                "cloudwatch:PutMetricData",
                "cloudwatch:GetDashboard",
                "cloudwatch:GetMetricData",
                "cloudwatch:DeleteAlarms",
                "events:PutRule",
                "logs:*",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:ListMetrics",
                "events:TestEventPattern",
                "events:PutPermission",
                "events:DescribeEventBus",
                "events:PutTargets",
                "cloudwatch:PutMetricAlarm",
                "cloudwatch:DeleteDashboards",
                "cloudwatch:DescribeAlarmHistory",
                "cloudwatch:EnableAlarmActions",
                "cloudwatch:DisableAlarmActions",
                "cloudwatch:DescribeAlarmsForMetric",
                "cloudwatch:ListDashboards",
                "cloudwatch:DescribeAlarms",
                "events:RemovePermission",
                "cloudwatch:SetAlarmState"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "events:*",
            "Resource": "arn:aws:events:*:*:rule/*"
        }
    ]
}`

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "events:PutEvents",
                "logs:PutDestinationPolicy",
                "events:PutRule",
                "logs:TestMetricFilter",
                "logs:DeleteDestination",
                "logs:CreateLogGroup",
                "events:TestEventPattern",
                "events:PutPermission",
                "events:DescribeEventBus",
                "events:PutTargets",
                "logs:DescribeExportTasks",
                "logs:DeleteResourcePolicy",
                "logs:PutResourcePolicy",
                "cloudwatch:*",
                "logs:CancelExportTask",
                "events:RemovePermission",
                "logs:DescribeResourcePolicies",
                "logs:PutDestination",
                "logs:DescribeDestinations"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "logs:ListTagsLogGroup",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:DescribeSubscriptionFilters",
                "logs:GetLogEvents",
                "logs:DescribeMetricFilters",
                "logs:FilterLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:log-group:*"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "logs:GetLogEvents",
            "Resource": "arn:aws:logs:*:*:log-group:*:*:*"
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": "logs:*",
            "Resource": [
                "arn:aws:logs:ap-southeast-2:*:log-group:/aws/connect/csb-prod",
                "arn:aws:logs:ap-southeast-2:*:log-group:/aws/connect/csb-prod:*:*"
            ]
        },
        {
            "Sid": "VisualEditor4",
            "Effect": "Allow",
            "Action": "events:*",
            "Resource": "arn:aws:events:ap-southeast-2:*:rule/CWATCH*"
        }
    ]
}`

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "apigateway:*",
            "Resource": "arn:aws:apigateway:*::*"
        }
    ]
}`

**Comment by casti3ll** [comment]
Hi, thanks for the details. Here are my comments:
- 1st policy fails at `{ "Sid": "VisualEditor1", "Effect": "Allow", "Action": "events:*", "Resource": "arn:aws:events:*:*:rule/*" }`
- 2nd policy fails at `{ "Sid": "VisualEditor4", "Effect": "Allow", "Action": "events:*", "Resource": "arn:aws:events:ap-southeast-2:*:rule/CWATCH*" }`

The reason why the jmespath search function fails is that it is looking for a list of actions in the JSON structure. Therefore, the correct way to write the policy should be with square brackets `[ ]` the `"Action": ["events:*"]` element. This way, the search function is not generating any false positives. Thanks!

**Comment by Pl4nky** [comment]
Ok, thanks for the explanation!

These policies were generated using the iam policy editor, so there are going to be situations where the brackets are missing. Other than manually modifying the policy when it crops up,  is there anything I can do in the lambda function to accommodate this?

**Comment by casti3ll** [comment]
This is the best approach I could find. Tried other versions for the jmespath search function but they are now generating false negatives which are also not acceptable. One more reason to double check the policy JSON.
