### ISSUE TITLE
CIS-EvaluateFullAdminPolicyPermissions not working as expected

### ISSUE THREAD

**Issue by gopikiran28** [aws-quickstart/quickstart-compliance-cis-benchmark#43]
There’s an issue with the lambda function “CIS-EvaluateFullAdminPolicyPermissions” created, that checks for policies to see if they have admin access while creating the Config rule "“CIS-EvaluateFullAdminPrivilegesPolicies”. The rule should mark a policy as non-compliant if it sees “Allow” Action * and resource * - but the current code says a rule is non-compliant even if the action is say ec2:Describe*. The code marks a rule non-compliant if there a wildcard (*) - no matter for what action (or) resource. Expectation is it should mark a rule as non-compliant only if the policy has 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}

But currently, its marking the rule as non-compliant even with the below policy,

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ec2:Describe*",
            "Resource": "*"
        }
    ]
}

Below is the code, lambda is using currently,

import boto3
import json
import jmespath
def evaluate_compliance(config_item, policy_arn):
  return_value = 'COMPLIANT'
  client = boto3.client('iam')
  # Get the policy details.
  policy = client.get_policy(PolicyArn = policy_arn)['Policy']
  # Get the latest policy version.
  policy_version = client.get_policy_version(
    PolicyArn = policy['Arn'],
    VersionId = policy['DefaultVersionId']
  )
  # search for full admin privileges within the policy statements
  if jmespath.search('PolicyVersion.Document.Statement[?Effect == \'Allow\' && contains(Resource, \'*\') && contains (Action, \'*\')]', policy_version):
    return_value = 'NON_COMPLIANT'
  return return_value
def lambda_handler(event, context):
  invoking_event = json.loads(event['invokingEvent'])
  compliance_value = 'COMPLIANT'
  if (invoking_event['configurationItem']['configurationItemStatus'] == "ResourceDeleted") or (invoking_event['configurationItem']['resourceType'] != 'AWS::IAM::Policy'):
    compliance_value = 'NOT_APPLICABLE'
  else:
    policy_arn = invoking_event['configurationItem']['ARN']
    compliance_value = evaluate_compliance(invoking_event['configurationItem'], policy_arn)
  config = boto3.client('config')
  response = config.put_evaluations(
    Evaluations=[
      {
        'ComplianceResourceType': invoking_event['configurationItem']['resourceType'],
        'ComplianceResourceId': invoking_event['configurationItem']['resourceId'],
        'ComplianceType': compliance_value,
        'OrderingTimestamp': invoking_event['configurationItem']['configurationItemCaptureTime']
      },
    ],
    ResultToken=event['resultToken']
  )

Seems like the issue is with line of the code, that's giving false positive results.

if jmespath.search('PolicyVersion.Document.Statement[?Effect == \'Allow\' && contains(Resource, \'*\') && contains (Action, \'*\')]', policy_version):

**Comment by Pl4nky** [comment]
Were your policies generated by the console policy editor?  That caused me some grief:

https://github.com/aws-quickstart/quickstart-compliance-cis-benchmark/issues/30

**Comment by gopikiran28** [comment]
Thanks for the info. Makes sense.
