### ISSUE TITLE
1.24 Ensure IAM policies that allow full "*:*" administrative privileges are not created

### ISSUE THREAD

**Issue by gowthamsubbu** [aws-quickstart/quickstart-compliance-cis-benchmark#6]
For 1.24 benchmark, Lambda function is not checking the complete policy and reporting below mentioned policy as Non-Compliance based on the first statement[0] .

Issue:
Following condition needs to be modified or additional conditions needs to be present to evaluate . Please evaluate considering NotResources, NotAction etc, since a policy might include all or many of these.

if jmespath.search('PolicyVersion.Document.Statement[?Effect == \'Allow\' && contains(Resource, \'*\') && contains (Action, \'*\')]', policy_version):
    return_value = 'NON_COMPLIANT'

Sample Policy:

{    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "*",
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "iam:UpdateAccountPasswordPolicy",
                "iam:DeleteAccountPasswordPolicy",
                "             
            ],
            "Resource": "*",
            "Effect": "Deny"
        }
    ]
}

**Comment by aravindkaws** [comment]
Thanks for send us this. We've added this to the backlog.
